
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
        name: "Terraform Format"

      - id: terraform_docs
        name: "Terraform Docs"
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true

      - id: terraform_tflint
        name: "Terraform Lint"

      - id: terraform_checkov
        name: "Terraform Security Check"
        args:
          - --args=--quiet
          - --args=--skip-check CKV_AWS_115,CKV_AWS_116
          - --args=--skip-check CKV_SECRET_6

  # Code quality check
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.34.0
    hooks:
      - id: semgrep
        name: "Code Quality Check"
        args:
          - --config=auto
          - --severity=ERROR
        exclude: |
          (?x)^(
            .*\.tfvars|
            .*secrets\.yaml|
            .*\.tfstate|
            .*\.tfstate\.backup|
            .*/\.terraform/.*
          )$