
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
        files: ^(.*/)*(.*\.tf)$
        exclude: \.terraform/.*
      - id: terraform_docs
        files: ^(.*/)*(.*\.tf)$
        exclude: \.terraform/.*
      - id: terraform_tflint
        files: ^(.*/)*(.*\.tf)$
        exclude: \.terraform/.*
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--skip-check CKV_AWS_115,CKV_AWS_116
          - --args=--skip-check CKV_SECRET_6
        files: ^(.*/)*(.*\.tf)$
        exclude: \.terraform/.*

  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.1
    hooks:
      - id: tfsec
        args:
          - --exclude-downloaded-modules
          - --ignore-hcl-errors
        files: ^(.*/)*(.*\.tf)$
        exclude: \.terraform/.*

  - repo: https://github.com/returntocorp/semgrep
    rev: v1.34.0
    hooks:
      - id: semgrep
        args: ['--config', 'auto']
        exclude: |
          (?x)^(
            .*\.tfvars|
            .*secrets\.yaml|
            .*\.tfstate|
            .*\.tfstate\.backup|
            .*/\.terraform/.*
          )$